### ISSUE TITLE
3.1.0 causes relative css paths to be broken for production builds

### ISSUE THREAD

**Issue by akshaisarma** [ember-cli/ember-cli-preprocess-registry#21]
This is a weird one but I narrowed it down to the version bump from 3.0.0 to 3.1.0. I suspect the underlying clean-css bump causes the issue. 

I have a project that uses ember-cli-sass, ember-cli-bootstrap-sassy, bootstrap-sass to use SCSS and get glyphicons into my project. When I build the project using ```ember build --environment=production```, the resulting minified css file has incorrect paths to the glyphicons font. ember-cli-bootstrap-sassy places them in dist/fonts/bootstrap and uses the paths ```'../fonts/bootstrap'``` but it seems the ```../``` is being stripped after the version bump.

Used versions:

Ember-CLI: 2.11 
Ember-CLI-Sass: 6.1.1
[Ember-CLI-bootstrap-sassy](https://github.com/lifegadget/ember-cli-bootstrap-sassy): 0.5.5

To reproduce:

1. Clone and install https://github.com/akshaisarma/relative-css-path-issue
2. ember build --environment=production
3. Check dist/assets/test-app-*.css for the url for the ```@font-face{font-family:'Glyphicons Halflings'.``` It should be ```url(fonts/bootstrap/glyphicons...)```, which is incorrect.
4. npm install -save-dev ember-cli-preprocess-registry@3.0.0
5. ember build --environment=production
6. Now dist/assets/test-app-*.css should have ```url(../fonts/bootstrap/glyphicons...)``` for the font-face, which is what is expected.

[This](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss#L83) is the variable that bootstrap-sass expands but the prefix is stripped out by the build process.

Let me know if you need anything else!

**Comment by nullrocket** [comment]
I have the same issue also.  One other result of the clean-css bump is that missing source maps are now errors instead of warnings, that is fine and probably a better default,  but it was definitely a breaking change for my build :)

**Comment by shinnn** [comment]
1. Since the release of clean-css v3, [`relativeTo` option has been renamed to `rebaseTo`](https://github.com/jakubpawlowicz/clean-css/blob/0b4ea6bb6de933ee10876ba0fe8543c3e8bc60ce/README.md#important-40-breaking-changes). 
2. In https://github.com/ember-cli/ember-cli-preprocessor-registry/pull/20, @rwjblue updated clean-css from v2 to v3 without major version  bump.
3. [`lib/broccoli/ember-app.js#L68`](https://github.com/ember-cli/ember-cli/blob/21a2e44619685d86327da1bb8b740e7a968f401a/lib/broccoli/ember-app.js#L68) in `ember-cli` no longer works.

The best solution is:

1. Revert https://github.com/ember-cli/ember-cli-preprocessor-registry/commit/70b8df09ca3e363cac24600a9880217eba60940a and publish `ember-cli-preprocess-registry` v3.1.1.
2. Restore https://github.com/ember-cli/ember-cli-preprocessor-registry/commit/70b8df09ca3e363cac24600a9880217eba60940a and publish `ember-cli-preprocess-registry` v4.0.0.

@rwjblue Read http://semver.org/ and learn semantic versioning. Most of npm modules, including `broccoli-clean-css`, follows the SemVer.

**Comment by rwjblue** [comment]
Perhaps I should learn about this "SemVer" thing.

**Comment by rwjblue** [comment]
I'll be reverting and releasing a 4.x in the next hour or so.

**Comment by akshaisarma** [comment]
v3.1.1 fixes it for me.
