### ISSUE TITLE
FYI: I unpublished 4.0.0

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli-preprocess-registry#50]
FYI: I unpublished 4.0.0 per @Turbo87's advice. I'm leaving this issue here so future travels can be aware, and so we can fill in the reason and blockers.

To do so @rwjblue I likely need some of your context.

**Comment by Turbo87** [comment]
@stefanpenner I think I managed to understand some of the context now:

- `ember-cli-preprocess-registry` is a direct dependency of `ember-cli` (which means users can't update it themselves)
- `ember-cli` passes the `minifyCSS` options to `ember-cli-preprocess-registry`, which in turn gets passed directly to `clean-css`
- `master` of this project no longer has the `clean-css` fallback
- in the end this means that we can't release a breaking change here without having to bump major for Ember CLI too :(

**Comment by jrjohnson** [comment]
Github started notifying me today that  several of my ember addons have a vulnerability for `clean-css < 4.1.11` https://github.com/jakubpawlowicz/clean-css/commit/2929bafbf8cdf7dccb24e0949c70833764fa87e3 I have no idea if it's a problem (not sure how `clean-css` is used) but given the way github screams about these alerts I wanted to mention it here.

**Comment by btecu** [comment]
I'm also getting the same warnings as @jrjohnson. What's the path forward?

**Comment by DuBistKomisch** [comment]
maybe a 3.3.1 with `broccoli-clean-css` bumped?

**Comment by gorner** [comment]
@DuBistKomisch Looks like that was attempted previously but had to be reverted: https://github.com/ember-cli/ember-cli-preprocess-registry/pull/27#discussion_r260734362

**Comment by rogeraraujo90** [comment]
@stefanpenner I can see that security issue is already fixed. Can this version be published now? Yarn Audit is blocking the CI in my project.

Thank you!

**Comment by gorner** [comment]
@rogeraraujo90 The issue at this point is that the security bug was only fixed in the 4.x stream of clean-css whereas this dependency relies on clean-css v3.x. There are some breaking changes in the clean-css config options from v3 to v4, so it can't be updated here without causing a breaking change to Ember CLI.

As suggested in the linked ember-cli issue above (https://github.com/ember-cli/ember-cli/issues/8579) your best bet is likely to add the updated clean-css to your yarn resolutions in package.json:

```json
"resolutions": {
  "clean-css": "4.2.1"
}
```

And then address any [breaking changes](https://github.com/jakubpawlowicz/clean-css#important-40-breaking-changes) that may be needed to any config options under the `minifyCSS` key in your app's ember-cli-build.js file.

**Comment by rogeraraujo90** [comment]
Thank you for the fast response @gorner! I'll proceed with your suggested workaround while wait for Ember 4.

**Comment by kategengler** [comment]
I want to re-release 4.0.0 and update the dependency for ember-cli 5.0. We can document how to add back the exact old clean-css behavior and also how to use the newest clean-css instead.

**Comment by kategengler** [comment]
Closing as I have now re-released the 4.x changes in 5.0(.1). https://github.com/ember-cli/ember-cli/pull/10244 Updates in ember-cli.
