### ISSUE TITLE
Broken fonts - on latest package.json update

### ISSUE THREAD

**Issue by theoldcounty** [ember-cli/ember-cli-preprocess-registry#56]
html5 fonts became broken

**Comment by gabrielcolombo** [comment]
Same issue here, for some reason the assets path became static.

**Comment by venkatamadhavareddysanikommu** [comment]
Link to the Issue : [In CSS files "../" is replaced with "" (empty string)](https://github.com/ember-cli/ember-cli-preprocess-registry/issues/51)

Yesterday update happened from v3.1.2 to v3.2.1. This is the commit diff as mentioned in the issue [Link](https://github.com/ember-cli/ember-cli-preprocess-registry/commit/59aeb88ef6b9f4580018bf2d97440fe063753125). All that was happened is in this 3.2.1 they updated _clean-css_ version. PR for that updation [Link](https://github.com/ember-cli/ember-cli-preprocess-registry/pull/55/files). Because of that we faced that issue. Yesterday we also faced the same issue.

We have added dependency _"ember-cli-preprocess-registry": "3.2.2"_ in our application and everything is working fine now. And one more thing, if you can remove this node module and try to reinstall, then this can be fixed. Because now this module will be updated new version (3.3.2). Follow one of the approach and you will be fine with your icons. Hope this might help you.

**Comment by Turbo87** [comment]
> We have added dependency _"ember-cli-preprocess-registry": "3.2.2"_ in our application and everything is working fine now

thanks for verifying this issue. seems like this is resolved by updating the dependency so I will go ahead and close this for now.
